# Generated by Django 4.2.8 on 2024-09-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.BigIntegerField(blank=True, default='+998', null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
