# Generated by Django 4.2.8 on 2024-09-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_message_timestamp_alter_message_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=models.BigIntegerField(blank=True, default=998, null=True),
        ),
    ]
